"""empty message

Revision ID: 2d247936fdf6
Revises: 3d4d942d9526
Create Date: 2014-08-13 03:03:57.285056

"""

# revision identifiers, used by Alembic.
revision = '2d247936fdf6'
down_revision = '3d4d942d9526'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'count')
    ### end Alembic commands ###
