"""empty message

Revision ID: a0d8d624a4c
Revises: 2d247936fdf6
Create Date: 2014-08-13 06:40:10.391860

"""

# revision identifiers, used by Alembic.
revision = 'a0d8d624a4c'
down_revision = '2d247936fdf6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
